// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AppPromoter AI - Crie Vídeos Promocionais com IA",
  description: "Transforme qualquer app em um vídeo viral em minutos. Geração automática de roteiros, narração IA, legendas dinâmicas e muito mais.",
  keywords: "vídeo promocional, IA, marketing digital, apps, TikTok, Reels, YouTube Shorts",
  openGraph: {
    title: "AppPromoter AI - Crie Vídeos Promocionais com IA",
    description: "Transforme qualquer app em um vídeo viral em minutos",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}